using fps.scripts;
// Generated by GDScriptToCSharpTypeConverter by Benjamin Eklund
using Godot;
using static Godot.GD;
using System;

public partial class PlayerWrapper : Node
{
    [Export]
    public CharacterBody3D WrappedNode;
    private Timer _timer;
    
    public override void _Ready() {
        _timer = GetNode<Timer>("Timer");
        _timer.Timeout += OnTimerTimeout;
    }
    
    public override void _Process(double delta) {

    }

    private void OnTimerTimeout() {
        
    }

    [Export] public bool CAPTURE_ON_START {
        get => (bool)WrappedNode.Get("CAPTURE_ON_START");
        set => WrappedNode.Set("CAPTURE_ON_START", value);
    }
    
    [Export] public float SPEED {
        get => (float)WrappedNode.Get("SPEED");
        set => WrappedNode.Set("SPEED", value);
    }
            
	
    [Export] public float ACCEL {
        get => (float)WrappedNode.Get("ACCEL");
        set => WrappedNode.Set("ACCEL", value);
    }
            
	
    [Export] public float IN_AIR_SPEED {
        get => (float)WrappedNode.Get("IN_AIR_SPEED");
        set => WrappedNode.Set("IN_AIR_SPEED", value);
    }
            
	
    [Export] public float IN_AIR_ACCEL {
        get => (float)WrappedNode.Get("IN_AIR_ACCEL");
        set => WrappedNode.Set("IN_AIR_ACCEL", value);
    }
            
	
    [Export] public float JUMP_VELOCITY {
        get => (float)WrappedNode.Get("JUMP_VELOCITY");
        set => WrappedNode.Set("JUMP_VELOCITY", value);
    }
            
	
    [Export] public bool HEAD_BOB {
        get => (bool)WrappedNode.Get("HEAD_BOB");
        set => WrappedNode.Set("HEAD_BOB", value);
    }
            
	
    [Export] public float HEAD_BOB_FREQUENCY {
        get => (float)WrappedNode.Get("HEAD_BOB_FREQUENCY");
        set => WrappedNode.Set("HEAD_BOB_FREQUENCY", value);
    }
            
	
    [Export] public float HEAD_BOB_AMPLITUDE {
        get => (float)WrappedNode.Get("HEAD_BOB_AMPLITUDE");
        set => WrappedNode.Set("HEAD_BOB_AMPLITUDE", value);
    }
            
	
    [Export] public bool CLAMP_HEAD_ROTATION {
        get => (bool)WrappedNode.Get("CLAMP_HEAD_ROTATION");
        set => WrappedNode.Set("CLAMP_HEAD_ROTATION", value);
    }
            
	
    [Export] public float CLAMP_HEAD_ROTATION_MIN {
        get => (float)WrappedNode.Get("CLAMP_HEAD_ROTATION_MIN");
        set => WrappedNode.Set("CLAMP_HEAD_ROTATION_MIN", value);
    }
            
	
    [Export] public float CLAMP_HEAD_ROTATION_MAX {
        get => (float)WrappedNode.Get("CLAMP_HEAD_ROTATION_MAX");
        set => WrappedNode.Set("CLAMP_HEAD_ROTATION_MAX", value);
    }
            
	
    [Export] public bool MOUSE_ACCEL {
        get => (bool)WrappedNode.Get("MOUSE_ACCEL");
        set => WrappedNode.Set("MOUSE_ACCEL", value);
    }
            
	
    [Export] public float KEY_BIND_MOUSE_SENS {
        get => (float)WrappedNode.Get("KEY_BIND_MOUSE_SENS");
        set => WrappedNode.Set("KEY_BIND_MOUSE_SENS", value);
    }
            
	
    [Export] public float KEY_BIND_MOUSE_ACCEL {
        get => (float)WrappedNode.Get("KEY_BIND_MOUSE_ACCEL");
        set => WrappedNode.Set("KEY_BIND_MOUSE_ACCEL", value);
    }
            
	
    [Export] public string KEY_BIND_UP {
        get => (string)WrappedNode.Get("KEY_BIND_UP");
        set => WrappedNode.Set("KEY_BIND_UP", value);
    }
            
	
    [Export] public string KEY_BIND_LEFT {
        get => (string)WrappedNode.Get("KEY_BIND_LEFT");
        set => WrappedNode.Set("KEY_BIND_LEFT", value);
    }
            
	
    [Export] public string KEY_BIND_RIGHT {
        get => (string)WrappedNode.Get("KEY_BIND_RIGHT");
        set => WrappedNode.Set("KEY_BIND_RIGHT", value);
    }
            
	
    [Export] public string KEY_BIND_DOWN {
        get => (string)WrappedNode.Get("KEY_BIND_DOWN");
        set => WrappedNode.Set("KEY_BIND_DOWN", value);
    }
            
	
    [Export] public string KEY_BIND_JUMP {
        get => (string)WrappedNode.Get("KEY_BIND_JUMP");
        set => WrappedNode.Set("KEY_BIND_JUMP", value);
    }
            
	
    [Export] public bool UPDATE_PLAYER_ON_PHYS_STEP {
        get => (bool)WrappedNode.Get("UPDATE_PLAYER_ON_PHYS_STEP");
        set => WrappedNode.Set("UPDATE_PLAYER_ON_PHYS_STEP", value);
    }
}
